[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"

# Redirect for Netlify Identity
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
